title: Subhamoy Biswas
description: <br>
             <font size="+1">
             <a href="https://subhamoybiswas.github.io/home/" class="active"><span class="item"><b>About</b></span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/projects.html"><span class="item"><b>Projects</b></span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/publications.html"><span class="item"><b>Publications</b></span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/awards.html"><span class="item"><b>Awards</b></span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/CV.html"><span class="item"><b>CV</b></span></a></font>
             <br>
             <br>
             <a href="mailto:s2biswas@uwaterloo.ca" target="_top"><b>Email</b></a> | <a href="https://github.com/SubhamoyBiswas/" target="_top"><b>GitHub</b></a> | <a href="https://www.linkedin.com/in/subhamoy-biswas-16869316a/" target="_top"><b>LinkedIn</b></a> | <a href="https://scholar.google.ca/citations?user=bHMeN1UAAAAJ&hl=en" target="_top"><b>Google Scholar</b></a> | <a href="https://www.instagram.com/__subhamoy.b/" target="_top"><b>Instagram</b>
             </a>
             <br>
email: s2biswas@uwaterloo.ca
theme: jekyll-theme-minimal
