title: Subhamoy Biswas
description: <font size="+1"><b><a href="mailto:s2biswas@uwaterloo.ca" target="_top"><img src="email.jpg" alt="alt text" height="40" align="middle"/></a> | <a href="https://github.com/SubhamoyBiswas/" target="_top">GitHub</a> | <a href="https://www.linkedin.com/in/subhamoy-biswas-16869316a/" target="_top">LinkedIn</a> | <a href="https://scholar.google.ca/citations?user=bHMeN1UAAAAJ&hl=en" target="_top">Google Scholar</a> | <a href="https://www.instagram.com/__subhamoy.b/" target="_top">Instagram</a></b></font>
email: s2biswas@uwaterloo.ca
theme: jekyll-theme-slate
