title: Subhamoy Biswas
description: <br>
             <font size="+1">
             <a href="https://subhamoybiswas.github.io/home/" class="active"><span class="item"><b>About</b></span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/projects.html"><span class="item"><b>Projects</b></span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/publications.html"><span class="item"><b>Publications</b></span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/awards.html"><span class="item"><b>Awards</b></span></a>
             <br>
             <a href="./CV.pdf"><span class="item"><b>CV</b></span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/contact.html"><span class="item"><b>Contact</b></span></a></font>
             <br>
             <br>
email: s2biswas@uwaterloo.ca
theme: jekyll-theme-minima
