title: Subhamoy Biswas
description: <br>
             <font size="+1">
             <a href="https://subhamoybiswas.github.io/home/" class="active"><span class="item">About</span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/projects.html"><span class="item">Projects</span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/publications.html"><span class="item">Publications</span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/awards.html"><span class="item">Awards</span></a>
             <br>
             <a href="https://subhamoybiswas.github.io/home/CV.html"><span class="item">CV</span></a></font>
             <br>
             <br>
             <b><a href="mailto:s2biswas@uwaterloo.ca" target="_top">Email</a> &emsp;| <a href="https://github.com/SubhamoyBiswas/" target="_top">GitHub</a> | <a href="https://www.linkedin.com/in/subhamoy-biswas-16869316a/" target="_top">LinkedIn</a> | <a href="https://scholar.google.ca/citations?user=bHMeN1UAAAAJ&hl=en" target="_top">Google Scholar</a> | <a href="https://www.instagram.com/__subhamoy.b/" target="_top">Instagram
             </a></b>
             <br>
email: s2biswas@uwaterloo.ca
theme: jekyll-theme-minimal
